### ISSUE TITLE
Resizing with single dimension gives internal server error

### ISSUE THREAD

**Issue by sedubois** [graphcool/serverless-image-proxy#1]
The following works:
https://images.graph.cool/cj1btogkaf14q010589c793ps/cj1m5r17c00iu0103i4ntokt5/500x300

But not this:
https://images.graph.cool/cj1btogkaf14q010589c793ps/cj1m5r17c00iu0103i4ntokt5/500x

I get `{"message": "Internal server error"}`.

**Comment by sedubois** [comment]
Similar issue with crop:
https://images.graph.cool/cj1btogkaf14q010589c793ps/cj1m5r17c00iu0103i4ntokt5/0x0:100x100

gives `{"message": "Internal server error"}`.

**Comment by sedubois** [comment]
@nilan just pinging to see if this issue was seen?

**Comment by marktani** [comment]
Sorry, just saw this.



> https://images.graph.cool/cj1btogkaf14q010589c793ps/cj1m5r17c00iu0103i4ntokt5/500x

The height is missing, working example: `https://images.graph.cool/cj1btogkaf14q010589c793ps/cj1m5r17c00iu0103i4ntokt5/500x500`

> https://images.graph.cool/cj1btogkaf14q010589c793ps/cj1m5r17c00iu0103i4ntokt5/0x0:100x100

This one is missing the `RESIZE` argument, working example: `https://images.graph.cool/cj1btogkaf14q010589c793ps/cj1m5r17c00iu0103i4ntokt5/0x0:100x100/200x200`

Refer to https://github.com/graphcool/serverless-image-proxy#syntax

**Comment by schickling** [comment]
@sedubois there are still a couple of limitations in this image service mostly based on [lovell/sharp](https://github.com/lovell/sharp). Would you mind taking a stab at it yourself and create a PR with the fix? This service is entirely standalone and should be fairly easy to debug.

**Comment by schickling** [comment]
Fixed. More here #4
