### ISSUE TITLE
EXIF Orientation flag is being discarded when cropping/resizing images

### ISSUE THREAD

**Issue by taikn** [graphcool/serverless-image-proxy#19]
When I upload an image with EXIF Orientation information, its not applied to the output image thus making it look flipped horizontally/vertically or rotated.

**Comment by taikn** [comment]
The EXIF Orientation is still being ignored...
here's the original uploaded data:
https://files.graph.cool/cj8a4l1ot02w90187fvh193ym/cj8syx0xo00xn0121b03o4epe

here's resized/cropped version:
https://images.graph.cool/v1/cj8a4l1ot02w90187fvh193ym/cj8syx0xo00xn0121b03o4epe/200x0:1200x800/576x384

**Comment by schickling** [comment]
Apologies @taikn, we haven't deployed the newest version yet. We'll soon write an update regarding file handling and image proxying.
