### ISSUE TITLE
Add `return` before line 37

### ISSUE THREAD

**Issue by tySwift93** [graphcool/serverless-image-proxy#3]
Look here: https://github.com/graphcool/serverless-image-proxy/blob/master/src/handler.ts#L37

I am assuming that, since `callback()` is getting called, the function should halt further execution.

**Comment by schickling** [comment]
Thanks for bringing this up. We're using [a helper function](https://github.com/graphcool/serverless-image-proxy/blob/master/src/handler.ts#L3) which allows for `async` functions and early returns. Behind the scenes it is actually calling the `callback()` function.
