### ISSUE TITLE
[Bug] Image is rotated, when I've just resized it.

### ISSUE THREAD

**Issue by Ranatchai** [graphcool/serverless-image-proxy#32]
Image is rotated 90degs, when I've just resized it.

### Original
https://images.graph.cool/v1/cj6eusnrx52qg0121i3gfa7db/cjbc5el7d00a90125dudmb86m/

### Resize to 200x400
https://images.graph.cool/v1/cj6eusnrx52qg0121i3gfa7db/cjbc5el7d00a90125dudmb86m/200x400

### Resize to 200x200
https://images.graph.cool/v1/cj6eusnrx52qg0121i3gfa7db/cjbc5el7d00a90125dudmb86m/200x200

**Comment by kbrandwijk** [comment]
I think you are running into the issue fixed here: https://github.com/graphcool/serverless-image-proxy/pull/31. I don't think there has been a new release yet after that PR was merged.

**Comment by schickling** [comment]
This should be fixed & deployed now. (Old images might still be cached in the wrong format.)
