### ISSUE TITLE
Feature request: Name of images

### ISSUE THREAD

**Issue by Huvik** [graphcool/serverless-image-proxy#7]
Hey, i was wondering if its possible to have name of image on end of url? 

`https://images.graph.cool/v1/__PROJECT_ID__/__FILE_SECRET__/500x300/__NAME__.jpg`

Reason for that is SEO, because when name of file match alt tag of img element. Images are indexed better with search engines. 

`<img src="https://images.graph.cool/v1/__PROJECT_ID__/__FILE_SECRET__/500x300/Graphcool.jpg" alt="Graphcool" />`

Will be better indexed then

`<img src="https://images.graph.cool/v1/__PROJECT_ID__/__FILE_SECRET__/500x300" alt="Graphcool" />`

Thx for response in advance.
Cheers Lukas

**Comment by schickling** [comment]
I don't see anything that would speak against that. Is that also how Imgix (or similar) handles it?

**Comment by Huvik** [comment]
Yea kind of, they use query string for example:
```
https://assets.imgix.net/setup/serving-swimmer.jpg?w=900&h=300&fit=crop&crop=entropy
```
So it would need change api little bit, or have it like penultimate part of URL.

**Comment by schickling** [comment]
I think your suggestion should make sense. Can you create a PR?
